[project]
name = "lab05"
version = "0.1.0"
description = "CPE 342 Lab 05"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jax>=0.4.20",
    "jinja2>=3.1.6",
    "keras>=3.0.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.5.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "tensorflow>=2.16.1",
    "torch>=2.1.0",
]

[dependency-groups]
dev = [
    "nbclient>=0.11.0",
    "nbconvert>=7.16.6",
    "nbformat>=5.11.0",
]
